### ISSUE TITLE
Attachements plugin with cds typer throws error

### ISSUE THREAD

**Issue by Beniseeger** [cap-js/attachments#68] opened 2024-06-14 14:47 UTC
When trying to integrate the attachments plugin into our CAP application we get the following errors: 

> `@cds-models/application/index.ts:414:46 - error TS2344: Type 'Attachments' does not satisfy the constraint 'readonly any[]'.
  Type 'Attachments' is missing the following properties from type 'readonly any[]': length, concat, join, slice, and 20 more.
414         attachments?: __.Composition.of.many<_.Attachments>;

and:

> @cds-models/index.ts:81:78 - error TS2552: Cannot find name '_AttachmentAspect'. Did you mean '_AttachmentsAspect'?
81 export class Attachments extends _managedAspect(_cuidAspect(_MediaDataAspect(_AttachmentAspect(__.Entity)))) {static drafts: typeof Attachments}`

The project is implemented with typescript and is using cds-typer plugin from sap (https://github.com/cap-js/cds-typer) to define types. After we integrated the attachements plugin via npm add @cap-js/attachments, then integrated it into our model and tryed to deploye it to our sqlite data base. We get the error written above. 

We are using the following versions: 
- cds: 7.9.2
- cds-dk: 7.9.3
- @cap-js/cds-typer: 0.21.2
- @cap-js/attachements: 1.1.1

**Comment by muskansethi1** [comment] 2024-06-25 05:58
Hi @Beniseeger,

Can you please share a sample or steps to reproduce the issue?

Best Regards,
Muskan

**Comment by jeevitha011** [comment] 2024-11-27 03:13
Hi @Beniseeger, 

I have tried replicating the error mentioned in the issue description using the [bookshop sample application](https://github.com/SAP-samples/cloud-cap-samples/tree/main/bookshop). After adding the `cds-typer` and `attachments `plugin as instructed, I was unable to reproduce the error that was reported.

I have attached the `schema.cds `and the generated `index.ts` for reference. 
[schema.cds.txt](https://github.com/user-attachments/files/17928252/schema.cds.txt)
[index.ts.txt](https://github.com/user-attachments/files/17928255/index.ts.txt)

Since the error could not be replicated on my end, I am closing this issue for now. Please feel free to provide additional context or steps if the error is still occurring.

Best Regards,
Jeevitha

**Closed by jeevitha011** 2024-11-27 03:13 UTC
Labels: author action
